@SOA.UsersAPI_HostAddress = http://localhost:5164




POST {{SOA.UsersAPI_HostAddress}}/admin/users/create
Content-Type: application/json

{
 "tenantId": "11111111-1111-1111-1111-111111111111",
  "email": "admin-created-user3@example.com",
  "password": "MyPass123!"
}

###
DELETE {{SOA.UsersAPI_HostAddress}}/admin/users/delete/{74f7b48a-490c-4137-8fc6-78a51309977c}

###

GET {{SOA.UsersAPI_HostAddress}}/admin/users/get-all

###

GET {{SOA.UsersAPI_HostAddress}}/admin/users/get/{898befcf-316d-4ba5-85a0-b001cf01d86f}

###

PUT {{SOA.UsersAPI_HostAddress}}/admin/users/update/{8c4700ef-750b-42a3-a018-70d6344fd876}
Content-Type: application/json

{
 "email": "updated@example.com",
  "isActive": false
}

###



POST {{SOA.UsersAPI_HostAddress}}/users/register
Content-Type: application/json
{
  "tenantId": "11111111-1111-1111-1111-111111111111",
  "email": "user7@example.com",
  "password": "MyPass123!"
}




###